# automatically generated by the FlatBuffers compiler, do not modify

# namespace: northstar

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CameraOutput(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCameraOutput(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CameraOutput()
        x.Init(buf, n + offset)
        return x

    # CameraOutput
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Microsecond timestamp (matches NT timestamp convention)
    # CameraOutput
    def TimestampUs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Camera index within the multi-camera module
    # CameraOutput
    def CameraIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Field-relative camera pose observation (null if no tags seen)
    # CameraOutput
    def CameraObservation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from northstar.CameraObservation import CameraObservation
            obj = CameraObservation()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frames per second (0 if not reported this cycle)
    # CameraOutput
    def Fps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def CameraOutputStart(builder): builder.StartObject(4)
def CameraOutputAddTimestampUs(builder, timestampUs): builder.PrependInt64Slot(0, timestampUs, 0)
def CameraOutputAddCameraIndex(builder, cameraIndex): builder.PrependInt32Slot(1, cameraIndex, 0)
def CameraOutputAddCameraObservation(builder, cameraObservation): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(cameraObservation), 0)
def CameraOutputAddFps(builder, fps): builder.PrependInt32Slot(3, fps, 0)
def CameraOutputEnd(builder): return builder.EndObject()
