# automatically generated by the FlatBuffers compiler, do not modify

# namespace: northstar

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CameraObservation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCameraObservation(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CameraObservation()
        x.Init(buf, n + offset)
        return x

    # CameraObservation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Primary pose solution (always present)
    # CameraObservation
    def Solution0(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from northstar.PoseSolution import PoseSolution
            obj = PoseSolution()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Alternate pose solution (present for single-tag ambiguity)
    # CameraObservation
    def Solution1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from northstar.PoseSolution import PoseSolution
            obj = PoseSolution()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IDs of the tags used in this observation
    # CameraObservation
    def TagIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # CameraObservation
    def TagIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # CameraObservation
    def TagIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CameraObservation
    def TagIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def CameraObservationStart(builder): builder.StartObject(3)
def CameraObservationAddSolution0(builder, solution0): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(solution0), 0)
def CameraObservationAddSolution1(builder, solution1): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(solution1), 0)
def CameraObservationAddTagIds(builder, tagIds): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(tagIds), 0)
def CameraObservationStartTagIdsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def CameraObservationEnd(builder): return builder.EndObject()
