# automatically generated by the FlatBuffers compiler, do not modify

# namespace: northstar

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Pose3d(object):
    __slots__ = ['_tab']

    # Pose3d
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Pose3d
    def Translation(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # Pose3d
    def Rotation(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 24)
        return obj


def CreatePose3d(builder, translation_x, translation_y, translation_z, rotation_w, rotation_x, rotation_y, rotation_z):
    builder.Prep(8, 56)
    builder.Prep(8, 32)
    builder.PrependFloat64(rotation_z)
    builder.PrependFloat64(rotation_y)
    builder.PrependFloat64(rotation_x)
    builder.PrependFloat64(rotation_w)
    builder.Prep(8, 24)
    builder.PrependFloat64(translation_z)
    builder.PrependFloat64(translation_y)
    builder.PrependFloat64(translation_x)
    return builder.Offset()
