# automatically generated by the FlatBuffers compiler, do not modify

# namespace: northstar

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PoseSolution(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPoseSolution(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PoseSolution()
        x.Init(buf, n + offset)
        return x

    # PoseSolution
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PoseSolution
    def Pose(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from northstar.Pose3d import Pose3d
            obj = Pose3d()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PoseSolution
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def PoseSolutionStart(builder): builder.StartObject(2)
def PoseSolutionAddPose(builder, pose): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(pose), 0)
def PoseSolutionAddError(builder, error): builder.PrependFloat64Slot(1, error, 0.0)
def PoseSolutionEnd(builder): return builder.EndObject()
