# automatically generated by the FlatBuffers compiler, do not modify

# namespace: objectdetections

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DetectionFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DetectionFrame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDetectionFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DetectionFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DetectionFrame
    def Detections(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from objectdetections.Detection import Detection
            obj = Detection()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DetectionFrame
    def DetectionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DetectionFrame
    def DetectionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def DetectionFrameStart(builder):
    builder.StartObject(1)

def Start(builder):
    DetectionFrameStart(builder)

def DetectionFrameAddDetections(builder, detections):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(detections), 0)

def AddDetections(builder, detections):
    DetectionFrameAddDetections(builder, detections)

def DetectionFrameStartDetectionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDetectionsVector(builder, numElems):
    return DetectionFrameStartDetectionsVector(builder, numElems)

def DetectionFrameEnd(builder):
    return builder.EndObject()

def End(builder):
    return DetectionFrameEnd(builder)
