# automatically generated by the FlatBuffers compiler, do not modify

# namespace: dsv0

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CameraObservation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CameraObservation()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCameraObservation(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CameraObservation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Primary pose solution (always present)
    # CameraObservation
    def Solution0(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from dsv0.PoseSolution import PoseSolution
            obj = PoseSolution()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Alternate pose solution (present for single-tag ambiguity)
    # CameraObservation
    def Solution1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from dsv0.PoseSolution import PoseSolution
            obj = PoseSolution()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IDs of the tags used in this observation
    # CameraObservation
    def TagIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # CameraObservation
    def TagIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # CameraObservation
    def TagIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CameraObservation
    def TagIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def CameraObservationStart(builder):
    builder.StartObject(3)

def Start(builder):
    CameraObservationStart(builder)

def CameraObservationAddSolution0(builder, solution0):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(solution0), 0)

def AddSolution0(builder, solution0):
    CameraObservationAddSolution0(builder, solution0)

def CameraObservationAddSolution1(builder, solution1):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(solution1), 0)

def AddSolution1(builder, solution1):
    CameraObservationAddSolution1(builder, solution1)

def CameraObservationAddTagIds(builder, tagIds):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(tagIds), 0)

def AddTagIds(builder, tagIds):
    CameraObservationAddTagIds(builder, tagIds)

def CameraObservationStartTagIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTagIdsVector(builder, numElems):
    return CameraObservationStartTagIdsVector(builder, numElems)

def CameraObservationCreateTagIdsVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependInt32(item)
    return builder.EndVector()

def CreateTagIdsVector(builder, data):
    CameraObservationCreateTagIdsVector(builder, data)

def CameraObservationEnd(builder):
    return builder.EndObject()

def End(builder):
    return CameraObservationEnd(builder)
