# automatically generated by the FlatBuffers compiler, do not modify

# namespace: dsv0

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Combined camera results; field-to-robot
class CombinedResults(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CombinedResults()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCombinedResults(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CombinedResults
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Field-relative robot pose observation (null if no tags seen)
    # CombinedResults
    def CameraObservation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from dsv0.CameraObservation import CameraObservation
            obj = CameraObservation()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frames per second (0 if not reported this cycle)
    # CombinedResults
    def Fps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def CombinedResultsStart(builder): builder.StartObject(2)
def Start(builder):
    return CombinedResultsStart(builder)
def CombinedResultsAddCameraObservation(builder, cameraObservation): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(cameraObservation), 0)
def AddCameraObservation(builder, cameraObservation):
    return CombinedResultsAddCameraObservation(builder, cameraObservation)
def CombinedResultsAddFps(builder, fps): builder.PrependInt32Slot(1, fps, 0)
def AddFps(builder, fps):
    return CombinedResultsAddFps(builder, fps)
def CombinedResultsEnd(builder): return builder.EndObject()
def End(builder):
    return CombinedResultsEnd(builder)