# automatically generated by the FlatBuffers compiler, do not modify

# namespace: dsv0

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Top-level message containing results from all cameras in a single frame
class Frame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Frame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Frame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Frame
    def ResultsType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Either per-camera or combined results
    # Frame
    def Results(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def FrameStart(builder): builder.StartObject(2)
def Start(builder):
    return FrameStart(builder)
def FrameAddResultsType(builder, resultsType): builder.PrependUint8Slot(0, resultsType, 0)
def AddResultsType(builder, resultsType):
    return FrameAddResultsType(builder, resultsType)
def FrameAddResults(builder, results): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(results), 0)
def AddResults(builder, results):
    return FrameAddResults(builder, results)
def FrameEnd(builder): return builder.EndObject()
def End(builder):
    return FrameEnd(builder)