# automatically generated by the FlatBuffers compiler, do not modify

# namespace: dsv0

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Top-level message containing results from all cameras in a single frame
class Frame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Frame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Frame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Microsecond timestamp for the frame capture
    # Frame
    def TimestampUs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Per-camera results
    # Frame
    def Cameras(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from dsv0.CameraOutput import CameraOutput
            obj = CameraOutput()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frame
    def CamerasLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Frame
    def CamerasIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def FrameStart(builder):
    builder.StartObject(2)

def Start(builder):
    FrameStart(builder)

def FrameAddTimestampUs(builder, timestampUs):
    builder.PrependInt64Slot(0, timestampUs, 0)

def AddTimestampUs(builder, timestampUs):
    FrameAddTimestampUs(builder, timestampUs)

def FrameAddCameras(builder, cameras):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(cameras), 0)

def AddCameras(builder, cameras):
    FrameAddCameras(builder, cameras)

def FrameStartCamerasVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCamerasVector(builder, numElems):
    return FrameStartCamerasVector(builder, numElems)

def FrameEnd(builder):
    return builder.EndObject()

def End(builder):
    return FrameEnd(builder)
