# automatically generated by the FlatBuffers compiler, do not modify

# namespace: dsv0

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PerCameraResults(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PerCameraResults()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPerCameraResults(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PerCameraResults
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PerCameraResults
    def Results(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from dsv0.CameraOutput import CameraOutput
            obj = CameraOutput()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PerCameraResults
    def ResultsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PerCameraResults
    def ResultsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def PerCameraResultsStart(builder): builder.StartObject(1)
def Start(builder):
    return PerCameraResultsStart(builder)
def PerCameraResultsAddResults(builder, results): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(results), 0)
def AddResults(builder, results):
    return PerCameraResultsAddResults(builder, results)
def PerCameraResultsStartResultsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartResultsVector(builder, numElems):
    return PerCameraResultsStartResultsVector(builder, numElems)
def PerCameraResultsEnd(builder): return builder.EndObject()
def End(builder):
    return PerCameraResultsEnd(builder)